# Generated by Django 4.2.13 on 2024-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("QUIZMASTER", "Quizmaster")],
                max_length=30,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
